### ISSUE TITLE
User Story 5: Edit Construction Sites

### ISSUE THREAD

**Issue by Faibs7** [Faibs7/capstone-project#10]
## Value proposition

As a User
I want to edit/update my existing construction sites
In order to change the polisher, date etc.

## Description

<img width="943" alt="Bildschirmfoto 2023-09-06 um 12 48 29" src="https://github.com/Faibs7/capstone-project/assets/72128103/1bfbb94c-f978-4963-905e-1535fb159501">

## Acceptance criteria

- [ ] display edit  and safe button
- [ ] edit and update one construction site 
- [ ] show new changes in the teaser element

## Tasks

- [ ] create a branch feat/edit-construction-sites
- [ ] create a new button "edit"
- [ ] create the feature to edit/update all form fields

**Comment by milodevhh** [comment]
Hey Fabian, in your Acceptance criteria you can explain or describe the areas in more detail, so they hardly differ from your listing in the tasks.
