### ISSUE TITLE
User Story (6): Restructuring, Refactoring, App Styling

### ISSUE THREAD

**Issue by Faibs7** [Faibs7/capstone-project#12]
## Value proposition

As a user
I want to have a simple but beautiful app with a clear, simple and well-named structure.
In order to meet the requirements of the user

## Description

- Refactoring,Restructuring for Components (Button, Form, Detail, List etc.)
- Header and Navbar with Styling and a purpose
- Details Page with all Informations and two buttons (Delete, Edit)
- Styling: Simple Background Color or a Construction Image
- Styling all Components and tags for the final app

## Acceptance criteria

- [ ] display the header with a svg and a h1
- [ ] display the styling of the app, each components and all used tags
- [ ] display the correct details page with all informations and the two buttons (delete, edit)
- [ ] better code structure

## Tasks

- [ ] create a branch feat/restruct-refact-styling
- [ ] create styling for the tags and components
- [ ] create a header with an svg
- [ ] create the new navbar
- [ ] split the code for more readability and a better structure
- [ ] general styling (mobile, background, font etc.)
