### ISSUE TITLE
User Story 4: delete construction-sites

### ISSUE THREAD

**Issue by Faibs7** [Faibs7/capstone-project#5]
## Value proposition

As a user
I want to be able to delete a construction site that has been created.
In order to delete an old construction site

## Description
<img width="667" alt="Bildschirmfoto 2023-08-28 um 09 46 53" src="https://github.com/Faibs7/capstone-project/assets/72128103/cf858991-8009-4911-a462-9947e5130526">

## Acceptance criteria

- [ ] display a delete button at the end of the details page (construction site)
- [ ] display a pop up with "do you really want to delete the site"
- [ ] deleting the construction site

## Tasks

- [ ] create a Branch feat/delete-construction-site
- [ ] create the function to delete the opened construction site
- [ ] create the pop up/site to ask the user "really delete yes/no"
- [ ] styling the pop up/site

**Comment by FabianRuettgers** [comment]
My Suggestions :
- You've mentioned having a pop-up with "really delete yes/no." Consider using more descriptive button labels like "Delete/Löschen" and "Cancel/Abbrechen" or "Confirm/Bestätigen"

**Comment by Faibs7** [comment]
Thank you Fabian, this was implemented directly
